---
apiVersion: v1
kind: Namespace
metadata:
  name: cdc-bootcamp
  labels:
    name: cdc-bootcamp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-fery
  namespace: cdc-bootcamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-fery
  template:
    metadata:
      labels:
        app: app-fery
    spec:
      containers:
        - name: container-fery
          image: 872583825157.dkr.ecr.ap-southeast-1.amazonaws.com/demo-fery
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-fery
  namespace: cdc-bootcamp
spec:
  selector:
    app: app-fery
  ports:
    - port: 8080
      targetPort: 8080